### PR TITLE
Add complex response components

### LINKED ISSUE #51: Add Utility Extensions
Some services and models could use some utility extensions.

I will add a `Blockfrost.Api.Services.Extensions` namespace, and `Blockfrost.Api.Models.Extensions` namespace to the main project so they are available by default.

### PR DESCRIPTION
**Pull request by tweakch**
## Description

* Added generated Unit Tests for Services
* Added default query parameters
* Added Models for complex property types. 
* Added utility extensions for AmountCollection and Amount to sum by asset. 
* Added docs
* Applied OpenApiSpec 0.1.28
* Fix file encodings
* Updated the NET5.0 samples
* Updated the README 
* Updated samples
* Updated Method Signatures => 0.3.0

## Related issues 

- [x] #28
- [x] #37 
- [x] #51 
- [x] #52

### CODE REVIEW

**Comment by tweakch** [comment]
a85c58f WIP

**Comment by soyfrien** [comment]
@mmahut @vladimirvolek 

Would you please look at this, or consider giving @tweakch the necessary permissions to move the project along.

**Comment by mmahut** [comment]
@tweakch all good to merge this?

**Comment by slowbackspace** [comment]
@mmahut looks like this PR is superseded by https://github.com/blockfrost/blockfrost-dotnet/pull/55 since it includes last commit from this PR. I'll close it.

**Pull request closed without merging**
