### PR TITLE
feat/issue-60

### PR DESCRIPTION
**Pull request by lilpaul**
adding preprod and preview networks to constants and blockfrostextensions

### CODE REVIEW

**Comment by cardano-dev4** [comment]
@eddex @mmahut @tweakch 

It appears the Cardano Testnet is down so this PR is to update the available networks / apis to support the preprod and preview testnets.

Let us know if you are able to take a look

**Review by eddex — APPROVED** [review]
lgtm

Edit: I'm not an official reviewer in this repo. Haven't done anything in a long time. But I still follow the development. :)

**Comment by lilpaul** [comment]
thanks guys, lets see if alex or marek have a look sometime and advise. i suspect they are the only ones with official pr review permissions, so getting it merged will require their involvement i think. there may be other things that need to be done in the PR around versioning and getting the build process done through to nuget publishing

**Comment by mmahut** [comment]
Thank you for the contribution! I will give it a try tomorrow :)

**Comment by mmahut** [comment]
@lilpaul please, if possible, keep the `testnet` as default. We will rewrite the tests for `preprod` in the future, but given it is going to be respinned as a network after the Vasil HF, we will do it only then.

**Comment by lilpaul** [comment]
Cool, I've reverted the change to launchSettings.json
no problem, main thing i was trying to achieve was allowing the new networks to be specified when we're doing DI setup, which I think the changes to constants and BlockfrostServiceExtensions will do?
Please let me know if there is anything else that needs to be done to get the above working and I'll sort it out.

**Review by mmahut — APPROVED** [review]

**Pull request merged**
