### PR TITLE
bfapi (v1) / bfcli (v0.4)

### LINKED ISSUE #54: Generate CLI commands
The `bfcli` is missing service commands:

`usage: bfcli [service] (command (subcommand)) (parameters) (--switch)`

- [x] Addresses
- [ ] Assets
- [x] Blocks
- [ ] Epochs
- [ ] Health (Common)
- [ ] Ledger
- [ ] Metrics (Common)

### LINKED ISSUE #58: Update samples and docs for v1
Some of the samples and documentation need to be updated in preparation for v1. 

- [X] Update [migration guide](https://github.com/blockfrost/blockfrost-dotnet/wiki/Migration-Guide)
- [ ] Update samples
- [ ] Update readme

### PR DESCRIPTION
**Pull request by tweakch**
## Related Issues
- [x] #54

### CODE REVIEW

**Review by soyfrien — APPROVED** [review]
I was stuck on the README.md. Approved.

**Review by soyfrien — APPROVED** [review]
These instructions actually work. :)

**Review by soyfrien — APPROVED** [review]
7/479 files viewed seem fine.

**Comment by soyfrien** [comment]
closes #58

**Review by slowbackspace — APPROVED** [review]
approving since the version from this branch is already published and most people are already using it as v1.0.0. Just be aware that the version 1.0.1 (published as v1 by mistake) is really the version before this PR (v0.x) with added preview/preprod support. So people going from v1.0.0 to to-be-released version are fine, but upgrading from 1.0.1 to  to-be-released version will be PITA as they are not compatible.

**Pull request merged**
